name: Check IMD Weather Forecast

on:
  schedule:
    # Runs every 3 hours (At minute 0 of every 3rd hour)
    - cron: '0 */3 * * *'
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub UI anytime

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Weather Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Commit updated cache file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last_forecast.txt
          git commit -m "Update last forecast cache [skip ci]" || exit 0
          git push
